# Importing pytorch and checking it

In [ ]:
import torch

x = torch.Tensor([5, 3])
y = torch.Tensor([2, 1])

print(x * y)

# pytorch is very similar to numpy. The difference is pytorch can perform matrix calculations on a GPU. Notice the familiar methods resembling numpy methods.

In [3]:
x = torch.zeros([2, 5])
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [4]:
x.shape

torch.Size([2, 5])

In [6]:
y = torch.rand([2, 5])
print(y)

tensor([[0.6666, 0.4327, 0.5153, 0.5470, 0.7817],
        [0.9177, 0.9113, 0.3972, 0.8922, 0.7879]])


# Reshaping in torch

In [7]:
#Reshaping from size 2x5 to size 1x10. Then assign it back to y.
y = y.view([1, 10])
print(y)

tensor([[0.6666, 0.4327, 0.5153, 0.5470, 0.7817, 0.9177, 0.9113, 0.3972, 0.8922,
         0.7879]])
